workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Initialize and Fix Android
        script: |
          flutter create .
      - name: Get Dependencies
        script: |
          flutter pub get
      - name: Generate Splash Screen
        script: |
          # 파일이 없을 경우를 대비해 에러를 무시하고 진행합니다.
          flutter pub run flutter_native_splash:create || true
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
