workflows:
  android-workflow:
    name: Android Release Build
    working_directory: . 
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Clean and Recreate Android Folder
        script: |
          # 기존 설정을 지우고 깨끗하게 다시 시작합니다.
          flutter clean
          rm -rf android
          flutter create --platforms android .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          # --clean 옵션을 빼고 빌드 명령어를 실행합니다.
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
