workflows:
  android-workflow:
    name: Bike Fit Final Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Clean and Create Project
        script: |
          flutter clean
          flutter create --platforms android .
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: |
          # 빌드 번호를 200으로 설정하여 폰이 강제로 업데이트된 것으로 인식하게 함
          flutter build apk --release --build-name=1.5.0 --build-number=200
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
