workflows:
  flutter-android-release:
    name: Over the Bike Fit - Android Release Build
    # ... 생략 ...
    instance_type: mac_mini_m2
    
    # 여기에 실제 프로젝트 폴더명을 입력하세요 (중요!)
    working_directory: 프로젝트_폴더명 

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      # ... 이하 동일 ...
