workflows:
  flutter-android-release:
    name: Flutter Android Release Build
    max_build_duration: 180  # 시간 여유롭게 늘림
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      cancel_previous_builds: true
    environment:
      flutter: stable
    scripts:
      - name: Debug working directory and structure
        script: |
          pwd
          ls -la
          find . -name pubspec.yaml
      - name: Force create android directory and local.properties
        script: |
          mkdir -p android
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
          cat android/local.properties || echo "local.properties creation failed"
      - name: Install dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/**/outputs/**/*.apk
      - flutter_driver.log
