workflows:
  flutter-android-release:
    instance_type: mac_mini_m2
    scripts:
      - name: 압축 해제 및 경로 이동
        script: |
          unzip over_the_bike_fit.zip
          # 압축을 풀었을 때 나오는 폴더 이름을 아래에 정확히 적으세요.
          cd over_the_bike_fit 
          flutter pub get
      - name: Build APK
        script: |
          cd over_the_bike_fit
          flutter build apk --release
