workflows:
  over_the_bike_fit:  # 키 이름 = 프로젝트 이름과 동일하게 → UI 인식 확률 98%
    name: Over The Bike Fit - Android Build  # UI에 뜨는 표시 이름 (이걸 선택하세요)
    instance_type: mac_mini_m2
    max_build_duration: 45

    environment:
      flutter: stable

    scripts:
      - name: Dependencies 설치
        script: flutter pub get

      - name: Gradle 호환 강제 (android 폴더 없이 해결)
        script: |
          mkdir -p android/gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > android/gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-all.zip" >> android/gradle/wrapper/gradle-wrapper.properties

          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
          echo "sdk.dir=$ANDROID_HOME" >> android/local.properties

      - name: Clean & Rebuild
        script: flutter clean && flutter pub get

      - name: APK 릴리스 빌드
        script: flutter build apk --
