workflows:
  flutter-android:
    name: Bike Fit Build Final
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Prepare Project and Assets
        script: |
          unzip *.zip
          # 프로젝트 폴더 찾기
          PROJ_PATH=$(find . -maxdepth 2 -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          cd "$PROJ_PATH"
          
          # assets 폴더를 만들고 업로드하신 이미지를 강제로 복사합니다
          mkdir -p assets
          cp ../assets_final/*.png ./assets/ 2>/dev/null || cp ../assets/*.png ./assets/ 2>/dev/null || true
          
          # 안드로이드 설정 복구 및 패키지 설치
          flutter create . --platforms android
          flutter pub get
          
      - name: Build APK
        script: |
          PROJ_PATH=$(find . -maxdepth 2 -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          cd "$PROJ_PATH"
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/app-release.apk"
