workflows:
  android-workflow:
    name: Android Release Build
    # 저장소 루트에 pubspec.yaml이 있다면 아래처럼 마침표(.) 하나만 찍으세요.
    working_directory: . 
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
